(function(f){function F(a){"$ignore"===a&&(e.define=x,x=null)}function G(a,b,c){c||(c=b,b=[]);g=0;y[a]=!0;l(b,function(){m[a]=c.apply(null,arguments)})}function l(){n.push(arguments);z()}function z(){var a,b,c,d,h,e,f,g;if(n.length){a=n;n=[];e={};k=[];for(b=a.length;b--;){d=[];f=!0;for(c=a[b][0].length;c--;)h=a[b][0][c],h in m?d[c]=m[h]:(e[h]||y[h]||(k.push(h),e[h]=!0),f&&(n.push(a[b]),f=!1));if(f){g=!0;try{a[b][1].apply(null,d)}catch(l){p(l,"runtime")}}}g?z():n.length&&!q&&(q=u(A,100))}}function A(){var a,
b,c,d,e=[];q=B(q);if(!g){v=B(v);for(a=k.length;a--;)d=k[a],r[d]?(k.splice(a,1),2>r[d]&&(r[d]++,e.push(d))):r[d]=1;g=k.length;e.length&&p(Error("Modules '"+e.join("', '")+"' failed to load"),"loadFailed");if(g){v=u(H,6E4);try{b=t.createElement("script"),b.src=I+"//s1.adformdsp.net/stoat/572/s1.adformdsp.net/load/v/0.0.70/e/"+m.$env.$hash()+"/i/"+m.$ignore+"/r:"+k.sort().join(":"),c=t.__gEBTN__("script")[0],b.onerror=J,c.parentNode.insertBefore(b,c)}catch(f){p(f,"script_insert")}}}}function J(){w("response_error",this.src)}function H(){g=
0;A()}function w(a,b,c){var d;Math.random()<(c||.03)&&(d=f.Adform)&&(d=d.Log)&&d.sendMessage&&d.sendMessage(a,""+b)}function p(a,b){var c=""+(a.stack||a);0>c.indexOf(a.message||"")&&(c=a+"\n"+c);u(function(){throw c;},0);w(b,c)}function C(){for(var a=arguments,b=0,c=a.length,d=[];b<c;b++)K(a[b])||d.push(a[b]);return d.length?D.apply(e,d):e.length}function K(a){function b(b){b.apply(null,a.slice(1))}var c=a[0],d=m[c];d?b(d):l([c],b)}var x,D,q,v,k,e=f._adfq||(f._adfq=[]),t=f.document,u=f.setTimeout,
B=f.clearTimeout,E=f.Adform,I="https:"===(E&&(E.shost||"").split("/")[0]||f.location.protocol)?"https:":"http:",m={require:l,$boot:{window:f,require:l,rethrow:p,log:w}},g=0,n=[],y={},r={};t.__gEBTN__=t.getElementsByTagName;(function(){var a;e.define?e.define=F:(D=e.push,e.define=G,e.push=C,a=e.slice(),e.length=0,C.apply(e,a))})()})(window);
(function(a,b,c,v,u){
a(b,[c],function(S){function F(f){return f}function V(){function f(){for(var p=1,b=n;p<k.length&&!k[p];p++)b=b.parent;try{return b==b.Function("return window")()}catch(a){}}function q(p,b){var a=b.charAt(0).toUpperCase()+b.slice(1);return r(p,b,"ms"+a,"moz"+a,"webkit"+a)}function r(a){for(var b=arguments,c=b.length;--c;)if(b[c]in a)return b[c]}function c(a,b){return 0<=(""+a).toLowerCase().indexOf(b.toLowerCase())}var e=S.window,d=e.document,t=d.documentElement,u=e.navigator,n=e.parent,g=
u.vendor,a=u.userAgent,v=d.createElement("div"),k=function(a){for(var b,c=100,e=a.top,d=[!0];--c&&a&&a!=e&&a!=a.parent;){try{b=!!(a=a.parent).Image}catch(f){b=!1}d.push(b)}return d}(e),l=e!=n,G=!l||k[1],B=!l||k[k.length-1],H=l&&f(),A=function(){var a,b=u.plugins,c=u.mimeTypes,d=e.ActiveXObject,f=26,b=b&&b["Shockwave Flash"]&&(!c||!c["application/x-shockwave-flash"]||c["application/x-shockwave-flash"].enabledPlugin)&&(b["Shockwave Flash"].version||b["Shockwave Flash"].description)||"";if(!b&&d)for(;6<=
f--;)try{a=new d("ShockwaveFlash.ShockwaveFlash."+f);6==f&&(a.AllowScriptAccess="always",b="WIN 6.0.21.0");try{b=a.GetVariable("$version").replace(/,/g,".")}catch(g){}break}catch(g){}return parseFloat(b.replace(/^.*?(\d+[\.,].*$)/,"$1").replace(/(^\d+\.)|\./g,"$1"))||0}(),w=10.3<=A&&!B,T=q(d,"hidden"),I=!!T,m=/MSIE|Trident/i.test(a),U=m&&("Microsoft Internet Explorer"===u.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))?parseFloat(RegExp.$1):-1,v=r(v,"addEventListener"),x=c(g,"apple computer"),
C=c(a,"ipad"),D=c(a,"iphone"),y=C||D,h;h=y&&(h=/\sos\s(\d+)_\d+/i.exec(a))&&(h=4<h[1]>>0);var E=c(g,"google"),J=!y&&c(a,"android"),K="ontouchstart"in d||"ontouchstart"in e,L=(x||E)&&/(chrome|crios)+\/[\d\.]+\s/i.test(a),M=/Firefox\/[\d\.]+/i.test(a),N=c(a,"opera"),g=c(a,"opr")&&c(g,"opera software"),z=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&x,a=m&&(c(a,"IEMobile")||c(a,"WPDesktop")),O=z&&!("webkitRequestAnimationFrame"in e),P="screenX"in e,Q="outerWidth"in e,R="mozInnerScreenX"in
e,t=t.msContentZoomFactor,d=!(!d.fireEvent||!d.attachEvent),F=q(e,"requestAnimationFrame"),w=w&&!z&&(!m||11<=U);return{result:[l,G,B,H,w,I,m,v,x,C,D,y,h,E,J,K,L,M,N,g,z,a,O,P,Q,R,t,d,!1],exports:{nop:function(){},access:k,frame:l,accParent:G,accTop:B,isolate:H,flashVersion:A,flInScreen:w,hidden:T,hasHidden:I,isIE:m,ieVersion:U,addEvent:v,isApple:x,isIPad:C,isIPhone:D,isIOS:y,isIOSF:h,isGoogle:E,isAndroid:J,isTouch:K,isChrome:L,isFirefox:M,isOpera:N,isOperaWebkit:g,isSafari:z,isIEMobile:a,isSafari5OrLess:O,
screenX:P,outerWidth:Q,mozInnerScreenX:R,msZF:t,ieDomEvents:d,reqAni:F,isRad:!1,frame:l,accParent:G,accTop:B,isolate:H,flInScreen:w,hasHidden:I,isIE:m,addEvent:v,isApple:x,isIPad:C,isIPhone:D,isIOS:y,isIOSF:h,isGoogle:E,isAndroid:J,isTouch:K,isChrome:L,isFirefox:M,isOpera:N,isOperaWebkit:g,isSafari:z,isIEMobile:a,isSafari5OrLess:O,screenX:P,outerWidth:Q,mozInnerScreenX:R,msZF:t,ieDomEvents:d,isRad:!1}}}var A={$hash:function(){if(!n){for(var f=V(),q=f.result,f=f.exports,r=[],c=0,e=q.length,d=0,e=e+
(6-e%6)%6;c<e;c++)d=d<<1|!!q[c],5==c%6&&(r.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-".charAt(d)),d=0);for(c in f)A[c]=f[c];n=r.join("")}return n}},n;try{if(!Function("return ("+F+")(1)===1")())throw"Incorrect eval result";}catch(f){S.log("toString",f)}return A});
a(v,[c,b],function(m,d){var h=m.window,u=h.document,v=h.setTimeout;d.$hash();return function(a){var b,c,e,k,f,g,h=new Date;c=a.type;var n=a.placeId,w=/\.js(\?|$)/i,x=/\.swf(\?|$)/i,l=d.isIE,p=d.flashVersion,q=l&&10>d.ieVersion,l=!l&&21>p;b="standard"==a.type&&"flash"==a.subtype;var y=d.isSafari&&6.1<=d.safariVersion&&b,z=a.fVer||a.ADFVer||a.version,A=a.ADFPoliteSrc,r=a.sources||a.videoSources,t=["src","ADFFlash","ADFInitFlash","bsrc","ADFBuckup"];c=4==a.behavior?"Slider":c.charAt(0).toUpperCase()+
c.slice(1);b=["AdConstructor","types/"+c];if("Standard"==c){for(c=0;c<t.length;c++)(e=a[t[c]])&&(e.match(x)?k=e:e.match(w)?f=e:g=e);g&&q&&(f=0);g&&q&&(r=0);if(z>p||(g||f)&&(l||y))k=0;k?b.push("contents/FlashTag"):f?b.push("contents/HTML"):r&&b.push("contents/VideoTag");(!k&&!f&&g||A)&&b.push("contents/ImageTag")}m.require(b,function B(c){var b,d=c.cbuild;if(n)if(b=u.getElementById(n))a.placement=b.nextSibling||b.previousSibling,b.parentNode.removeChild(b),d(a);else if(1E4>new Date-h)v(function(){B(c)},
0);else throw Error("Failed to find placement");else d(a)})}});
a(u,function(){return"hYAAAAAAA"});
})(_adfq.define,"$env","$boot","$main","$ignore");